### ISSUE TITLE
Feature Request: GTA 3-style floating pickups

### ISSUE THREAD

**Issue by warriorstar-orion** [kagikn/GlowingPickups#1]
Hi there;

Would it be possible to add a GTA-3 style pickup, with floating and spinning in addition to the glow?

Something like this: https://youtu.be/lD_SQRP9I9s?t=24 (00:24 mark)

Thanks!

**Comment by kagikn** [comment]
You can create pickups that floats and slowly spins (you may see ones in GTA Online), but I don't know how to make existing pickups float and spin or how to draw coronas just like in 3D Era games. I'm sorry, but I don't have time to find the ways to do.
